name: molecule test

on:
  pull_request:
      branches:
          - main
      types: [opened, synchronize, reopened]
      paths:
        - 'defaults/**'
        - 'handlers/**'
        - 'molecule/**'
        - 'tasks/**'
        - 'templates/**'
        - 'vars/**'
  schedule:
      - cron: '0 1 1 * *'
  workflow_dispatch:

jobs:
  standalone:
    name: Test standalone setup
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        config:
          - image: "rockylinux8"
            tag: "latest"
          - image: "ubuntu2004"
            tag: "latest"
          - image: "ubuntu2204"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}

  cluster_keepalived:
    name: Test HA cluster with keepalived
    runs-on: ubuntu-20.04
    needs: standalone
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - image: "ubuntu2204"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          scenario: cluster

  cluster_kubevip:
    name: Test HA cluster with kube-vip
    runs-on: ubuntu-20.04
    needs: standalone
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - image: "ubuntu2204"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          scenario: ha_cluster_upgrade
